selectors = {
    "CATEGORY_LIST": "li.category-page__member",
    "CATEGORY_NAME": "a.category-page__member-link::text",
    "CATEGORY_THUMBNAIL": "img.category-page__member-thumbnail::attr(src)",
    "CATEGORY_URL": "a.category-page__member-link",
    "CATEGORY_NEXT_PAGE": "a.category-page__pagination-next::attr(href)",
    "PAGE_HEADER_TITLE": "h1.page-header__title::text",
    "CHARACTER_IMAGE": "a.image-thumbnail > img::attr(src)",
    "CHARACTER_THUMB_IMAGE": "img.thumbimage::attr(src)",
    "CHARACTER_NAME": "h2[data-source=name]::text",
    "CHARACTER_FEATURE_FILMS": "div[data-source=films] div.pi-data-value > i > a::text",
    "CHARACTER_SHORT_FILMS": "div[data-source=shorts] div.pi-data-value > i > a::text",
    "CHARACTER_SHOWS": "div[data-source=shows] div.pi-data-value > i > a::text",
    "CHARACTER_GAMES": "div[data-source=games] div.pi-data-value > i > a::text",
    "CHARACTER_RIDES": "div[data-source=rides] div.pi-data-value > i > a::text",
    "CHARACTER_ANIMATOR": "div[data-source=animator] div.pi-data-value > i > a::text",
    "CHARACTER_DESIGNER": "div[data-source=designer] div.pi-data-value > i > a::text",
    "CHARACTER_VOICE": "div[data-source=voice] div.pi-data-value > i > a::text",
    "CHARACTER_PORTRAYED_BY": "div[data-source=actor] div.pi-data-value > i > a::text, div[data-source=actress] div.pi-data-value > i > a::text",
    "CHARACTER_PERFORMANCE_MODEL": "div[data-source=model] div.pi-data-value > i > a::text",
    "CHARACTER_INSPIRATION": "div[data-source=inspiration] div.pi-data-value > i > a::text",
    "CHARACTER_AWARDS": "div[data-source=awards] div.pi-data-value > i > a::text",
    "CHARACTER_FULLNAME": "div[data-source=fullname] div.pi-data-value > i > a::text",
    "CHARACTER_OTHER_NAMES": "div[data-source=alias] div.pi-data-value > i > a::text",
    "CHARACTER_OCCUPATION": "div[data-source=occupation] div.pi-data-value > i > a::text",
    "CHARACTER_AFFILIATIONS": "div[data-source=affiliations] div.pi-data-value > i > a::text",
    "CHARACTER_HOME": "div[data-source=home] div.pi-data-value > i > a::text",
    "CHARACTER_LIKES": "div[data-source=likes] div.pi-data-value > i > a::text",
    "CHARACTER_DISLIKES": "div[data-source=dislikes] div.pi-data-value > i > a::text",
    "CHARACTER_POWERS": "div[data-source=powers] div.pi-data-value > i > a::text",
    "CHARACTER_PARAPHERNALIA": "div[data-source=paraphernalia] div.pi-data-value > i > a::text",
    "CHARACTER_STATUS": "div[data-source=status] div.pi-data-value > i > a::text",
    "CHARACTER_PARENTS": "div[data-source=parents] div.pi-data-value > i > a::text",
    "CHARACTER_SIBLINGS": "div[data-source=siblings] div.pi-data-value > i > a::text",
    "CHARACTER_FAMILY": "div[data-source=family] div.pi-data-value > i > a::text",
    "CHARACTER_PARTNER": "div[data-source=partner] div.pi-data-value > i > a::text",
    "CHARACTER_CHILDREN": "div[data-source=children] div.pi-data-value > i > a::text",
    "CHARACTER_PETS": "div[data-source=pets] div.pi-data-value > i > a::text",
}

characters_string_skip_list = [
    "Disney characters",
    "Category:",
    "User blog:",
    "Disney Prince",
    "Disney Princess",
]
