selectors = {
    "CATEGORY_LIST": "li.category-page__member",
    "CATEGORY_NAME": "a.category-page__member-link::text",
    "CATEGORY_THUMBNAIL": "img.category-page__member-thumbnail::attr(src)",
    "CATEGORY_URL": "a.category-page__member-link",
    "CATEGORY_NEXT_PAGE": "a.category-page__pagination-next::attr(href)",
    "PAGE_HEADER_TITLE": "h1.page-header__title::text",
    "CHARACTER_IMAGE": "a.image-thumbnail > img::attr(src)",
    "CHARACTER_THUMB_IMAGE": "img.thumbimage::attr(src)",
    "CHARACTER_NAME": "h2[data-source=name]::text",
    "CHARACTER_FEATURE_FILMS": "div[data-source=films] div.pi-data-value > i > a::text",
    "CHARACTER_SHORT_FILMS": "div[data-source=shorts] div.pi-data-value > i > a::text",
    "CHARACTER_SHOWS": "div[data-source=shows] div.pi-data-value > i > a::text",
    "CHARACTER_GAMES": "div[data-source=games] div.pi-data-value > i > a::text",
    "CHARACTER_RIDES": "div[data-source=rides] div.pi-data-value > i > a::text",
    "CHARACTER_ANIMATOR": "div[data-source=animator] div.pi-data-value > i > a::text",
    "CHARACTER_DESIGNER": "div[data-source=designer] div.pi-data-value > i > a::text",
    "CHARACTER_VOICE": "div[data-source=voice] div.pi-data-value > i > a::text",
    "CHARACTER_PORTRAYED_BY": "div[data-source=actor] div.pi-data-value > i > a::text, div[data-source=actress] div.pi-data-value > i > a::text",
    "CHARACTER_PERFORMANCE_MODEL": "div[data-source=model] div.pi-data-value > i > a::text",
    "CHARACTER_INSPIRATION": "div[data-source=inspiration] div.pi-data-value > i > a::text",
    "CHARACTER_AWARDS": "div[data-source=awards] div.pi-data-value > i > a::text",
}

characters_string_skip_list = [
    "Disney characters",
    "Category:",
    "User blog:",
    "Disney Prince",
    "Disney Princess",
]
